name: Build ToU Overlay

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show directory contents (debug)
        run: |
          echo "== Current Directory =="
          dir
          echo "== Subdirectories =="
          dir /s

      - name: Add MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build DLL
        run: msbuild ToURoleOverlay.csproj /p:Configuration=Release
        working-directory: ./tou-build

      - name: Upload compiled DLL
        uses: actions/upload-artifact@v4
        with:
          name: ToURoleOverlay
          path: tou-build/bin/Release/ToURoleOverlay.dll
